### ISSUE TITLE
Make a block scheme of all the hardware

### ISSUE THREAD

**Issue by DylanVanAssche** [oSoc17/code9000#11]
Make a block scheme of all the hardware in order to see what we're building and which pieces are missing.

**Comment by DylanVanAssche** [comment]
Done! See here: https://drive.google.com/drive/folders/0B1tegZmzOjekZWE0U1hRN25IdUk

**Comment by DemianD** [comment]
@modulebaan , Can you update the Project here: https://github.com/oSoc17/code9000/projects/1
(Put it to Done, or Review)
And does someone have reviewed it already? (Maybe Synthia)

**Comment by DylanVanAssche** [comment]
Fixed it! Thanks @DemianD 
@cynthiav11 reviewed this already
