### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by th0rgall** [oSoc17/code9000#366]
Or at least I didn't get an email within 10 minutes.

When you click the button, a confirmation like 
>A mail to reset your password has been sent to dude@mail.com. 
Please wait x minutes for it to arrive. 
Didn't get it? Click [here]() to resend. [Change mail]() 

would be cool.

Great job on the app for the rest, cool stuff! :+1:

**Comment by DemianD** [comment]
@diegodewilde, can you look in the logs of Mailgun if a mail is send?

@th0rgall, thank you!
Is it possible that you check your spam folder?

**Comment by DemianD** [comment]
@th0rgall, I've fixed the issue.

There was a problem with a database migration, where there was no primary key and deleted_at field.

You can try again, and normally you would receive an email.

**Comment by th0rgall** [comment]
@DemianD Yup, looking good! There was a delay of a few minutes but all is working well now (mail + reset). Good job on the confimation message too!

I you feel like it you can delete one my 2 accounts now, to clean up the ranking board :D

**Comment by DemianD** [comment]
@th0rgall, I've deleted one of your accounts.

Let us know if you have any other improvements
