### ISSUE TITLE
Topbar buttons are not working on landing page.

### ISSUE THREAD

**Issue by mietcls** [oSoc17/code9000#367]
Tested here: https://birds.today/ on chrome — Version 60.0.3112.90 (Official Build) (64-bit).

![screen shot 2017-08-16 at 16 38 36](https://user-images.githubusercontent.com/1572885/29369045-bb79f5ae-82a1-11e7-82b2-9d0149c1d59f.png)

The links app and developers are not clickable because the "bubbles" are in front of them. You can fix this with z-index or via pointer-events. These are the "bubbles":

![screen shot 2017-08-16 at 16 41 39](https://user-images.githubusercontent.com/1572885/29369097-e50474da-82a1-11e7-9f73-81cfac1b05b8.png)

**Comment by DemianD** [comment]
Hi @mietcls,

Thank you for reporting the issue. It's currently fixed in #368.
Let us know if you have any other improvements
