### ISSUE TITLE
Prepare meeting with Yannick (FabLab)

### ISSUE THREAD

**Issue by cynthiav11** [oSoc17/code9000#39]
- Going over requested files
- Preparing questions to ask Yannick

**Comment by DylanVanAssche** [comment]
Files CHECK

**Comment by DylanVanAssche** [comment]
- Which things are important when we choose a solar panel and charger? 
- How much power should it give? Only running during the day
- Manhours: let's say 1 full time person max 3 days
- Knowledge in our team: limited, we can figure out the power consumption of the IOT but we don't know exactly what the best setup is (see block scheme)

**Comment by DylanVanAssche** [comment]
Next meeting: Thursday 13/07

**Comment by DylanVanAssche** [comment]
Example setup:

17 Ah, 12V Solar accu
http://www.conrad.be/ce/nl/product/110760/GNB-Sonnenschein-985006-Solar-accu-12-V-17-Ah-Loodgel-b-x-h-x-d-181-x-167-x-76-mm-M5-schroefaansluiting

Solar charger 4A
http://www.conrad.be/ce/nl/product/110173/200013-Solar-laadregelaar-12-V-24-V-4-A

Solar panels (2 pieces = 2x 20Wp)
http://www.conrad.be/ce/nl/product/110706/Dunne-film-zonnecellen-20-Wp-18-V?ref=list

12V -> 5V DC-DC stepdown
http://www.conrad.be/ce/nl/product/676229/RECOM-ROF-78E50-05SMD-R-DCDC-converter-component-12-VDC-24-VDC-5-VDC-500-mA-25-W-Aantal-uitgangen-1-x?ref=searchDetail
