### ISSUE TITLE
Collect data when a bird is detected

### ISSUE THREAD

**Issue by DylanVanAssche** [oSoc17/code9000#7]
- [x] Check for a PIR sensor trigger, otherwise sleep
- [x] Collect data from the sensors, camera, ... when PIR sensor is triggered
- [x] Check if data is valid and recollect when necessary

**Comment by DylanVanAssche** [comment]
Demo code does those things already :)

**Comment by DemianD** [comment]
Nice job, is the demo code already on GitHub?

**Comment by DylanVanAssche** [comment]
Yes, the file: testHardware.py does all this stuff.
I'm now building a more future proof version which also test for missing modules and stuff.
